# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('artist_lineup', models.CharField(max_length=30)),
            ],
        ),
    ]
