# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_festval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Festval',
            new_name='Festival',
        ),
    ]
